apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: default # kustomize会把所有资源自动注入这个namespace, 真实情况需要改动，首先考察是多集群/单集群多个namespace。

replicas:
  - name: hy-frontend
    count: 2

commonLabels:
  environment: prod

images:
  - name: frontend-img
    newName: temp-ci-will-override
